---
- name: Instalar Docker e Docker Compose
  hosts: local
  connection: local
  become: yes
  tasks:
    - name: Instalar pacotes necessários
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Criar diretório /etc/apt/keyrings
      file:
        path: /etc/apt/keyrings
        state: directory

    - name: Adicionar chave do Docker ao keyring do apt
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg

    - name: Adicionar repositório do Docker ao apt
      apt_repository:
        filename: docker
        repo: "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
        state: present

    - name: Atualizar cache do apt
      apt:
        update_cache: yes

    - name: Instalar Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Criar grupo docker
      group:
        name: docker
        state: present

    - name: Adicionar usuário ao grupo docker
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Carregar alterações de grupo para o usuário atual
      shell: newgrp docker

    - name: Habilitar serviços do Docker
      systemd:
        name: "{{ item }}"
        enabled: yes
      loop:
        - docker.service
        - containerd.service

    - name: Instalar Docker Compose
      shell: curl -L "https://github.com/docker/compose/releases/download/v2.2.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && sudo chmod +x /usr/local/bin/docker-compose
